In [297]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [298]:
import cv2, os
data_path = os.getcwd() + '\\dataset\\train'
data_path = data_path.replace("\\model", "")
categories= os.listdir(data_path)
labels = [i for i in range(len(categories))]

label_dict = dict(zip(categories,labels)) #empty dictionary


In [299]:
print(label_dict)
print(categories)
print(labels)

{'.DS_Store': 0, 'garbage': 1, 'organic': 2, 'recycling': 3}
['.DS_Store', 'garbage', 'organic', 'recycling']
[0, 1, 2, 3]


In [300]:
label_dict.pop(".DS_Store")

0

In [301]:
label_dict['garbage'] = 0
label_dict['organic'] = 1
label_dict['recycling'] = 2
label_dict

{'garbage': 0, 'organic': 1, 'recycling': 2}

In [302]:
categories

['.DS_Store', 'garbage', 'organic', 'recycling']

In [303]:
categories

['.DS_Store', 'garbage', 'organic', 'recycling']

In [304]:
labels.remove(3)

In [305]:
labels

[0, 1, 2]

In [306]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [307]:
data

array([[[[0.01568627, 0.08627451, 0.15294118],
         [0.02352941, 0.09411765, 0.16078431],
         [0.02745098, 0.09803922, 0.16862745],
         ...,
         [0.55294118, 0.78823529, 0.96078431],
         [0.55686275, 0.78823529, 0.96470588],
         [0.55686275, 0.78823529, 0.96470588]],

        [[0.03137255, 0.09019608, 0.16470588],
         [0.01960784, 0.09411765, 0.16470588],
         [0.01960784, 0.09803922, 0.17254902],
         ...,
         [0.54901961, 0.78823529, 0.96862745],
         [0.54901961, 0.78823529, 0.97254902],
         [0.54901961, 0.79215686, 0.97647059]],

        [[0.02352941, 0.07843137, 0.15686275],
         [0.01568627, 0.09019608, 0.16470588],
         [0.01960784, 0.10196078, 0.17254902],
         ...,
         [0.54901961, 0.78823529, 0.97254902],
         [0.54509804, 0.78823529, 0.97647059],
         [0.54901961, 0.79215686, 0.98039216]],

        ...,

        [[0.00784314, 0.01568627, 0.01960784],
         [0.00784314, 0.01568627, 0.02352941]

In [308]:
len(target)

234

In [309]:
import numpy as np
data=np.array(data)/255.0
data=np.reshape(data,(data.shape[0], img_size, img_size, 3))
target=np.array(target)

from keras.utils import to_categorical

newTarget = keras.utils.to_categorical(target)

In [310]:
newTarget.shape

(234, 3)

In [311]:
newTarget

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [312]:
data.shape

(234, 150, 150, 3)

In [313]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_path = os.getcwd() + '\\dataset\\train'
train_path = train_path.replace("\\model", "")
valid_path = os.getcwd() + '\\dataset\\validation'
valid_path = valid_path.replace("\\model", "")

# Assuming data is in 'train' directory with subdirectories for each class
datagen = ImageDataGenerator(validation_split=0.2, rescale=1./255)

# Load and preprocess training data
train_generator = datagen.flow_from_directory(train_path,
    target_size=(150, 150),  # Resize images to 100x100 pixels
    batch_size=32,
    class_mode='sparse',  # Use 'sparse' mode for sparse_categorical_crossentropy
    subset='training'
)

# Load and preprocess validation data
validation_generator = datagen.flow_from_directory(valid_path,
    target_size=(150, 150),  # Resize images to 100x100 pixels
    batch_size=32,
    class_mode='sparse',  # Use 'sparse' mode for sparse_categorical_crossentropy
    subset='validation'
)

Found 189 images belonging to 3 classes.
Found 9 images belonging to 3 classes.


In [314]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint

# Initialize model
model=Sequential()

#First CNN (convolutional neural network) Layer
model.add(Conv2D(234, (3,3), activation='relu', input_shape=data.shape[1:]))
model.add(MaxPooling2D(pool_size=(2,2)))

# Second convolution layer to get better accuracy on the images
model.add(Conv2D(100, (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

#Flatten layer to stack the out convolution from second layer
model.add(Flatten())

# Dense layer of 128 neurons
model.add(Dense(50,activation='relu'))

#Final Layer with 3 outputs for the 3 categories (garbage, organic, recycling)
model.add(Dense(3, activation='softmax'))


model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


c:\Users\labib\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [315]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_24 (Conv2D)              │ (None, 148, 148, 234)  │         6,552 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_22 (MaxPooling2D) │ (None, 74, 74, 234)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_25 (Conv2D)              │ (None, 72, 72, 100)    │       210,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_23 (MaxPooling2D) │ (None, 36, 36, 100)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_10 (Flatten)            │ (None, 129600)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 50)             │     6,480,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 3)              │           153 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,697,455 (25.55 MB)

 Trainable params: 6,697,455 (25.55 MB)

 Non-trainable params: 0 (0.00 B)

In [317]:
checkpoint = ModelCheckpoint('model.keras', monitor='val_accuracy', save_best_only=True, mode='max')

In [318]:
train_target

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

In [320]:
# Training the model
history = model.fit(
    train_generator, 
    epochs=50, 
    validation_data=validation_generator,
    callbacks=[checkpoint]
    )

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - accuracy: 1.0000 - loss: 6.9480e-04 - val_accuracy: 0.6667 - val_loss: 1.9167
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - accuracy: 1.0000 - loss: 5.6033e-04 - val_accuracy: 0.6667 - val_loss: 1.9085
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - accuracy: 1.0000 - loss: 6.0225e-04 - val_accuracy: 0.6667 - val_loss: 1.9226
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 10s 2s/step - accuracy: 1.0000 - loss: 6.2404e-04 - val_accuracy: 0.6667 - val_loss: 1.9415
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - accuracy: 1.0000 - loss: 5.0805e-04 - val_accuracy: 0.6667 - val_loss: 1.9504
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 10s 2s/step - accuracy: 1.0000 - loss: 4.9593e-04 - val_accuracy: 0.6667 - val_loss: 1.9696
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 10s 2s/step - accuracy: 1.0000 - loss: 3.8624e-04 - val_accuracy: 0.6667 - val_loss: 1.9830
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 11s 2s/step - accuracy: 1.0000 - loss: 5.5263e-04 - val_accuracy: 0.555

KeyboardInterrupt: 